default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  LOCAL_TIME_ZONE: "UTC"
  DEBUG: false
  PROFILING: true
  SECRET_KEY: ""
  SENTRY_DSN: ""
  SITE_ID: 0
  PRE_COMPILE: true

development:
  ALLOWED_HOSTS: ["7c4f8ed0b7fc.ngrok.io"]
  DEBUG: true
  PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  PRE_COMPILE: false

heroku:
  ALLOWED_HOSTS:
    - .xxxxxxweather.herokuapp.com
    - 127.0.0.1
    - localhost
  DEBUG: false
  PROFILING: 0
  PRE_COMPILE: false
  SECRET_KEY: "1"
